### ISSUE TITLE
TanStack devtools

### ISSUE THREAD

**Issue by Yordan-Ramchev** [MentorMate/create-vue#135]
Let's add devtools - https://tanstack.com/query/latest/docs/vue/devtools

**Comment by georgi-mateev** [comment]
TanStack provides two types of devtools - the first one integrates in the official Vue DevTools, the second is a component based one. We opted for the first one since it does not require an extra package, is automatically detected and most importantly the component based kind needs to be attached in `App.vue` which will create additional variations of the code template while the first approach is much cleaner.

<img width="197" alt="vue-query-devtools" src="https://github.com/MentorMate/create-vue/assets/95027221/a065c195-611b-4113-b0e0-88570e2b6fda">
